import {
  Controller,
  Post,
  Get,
  Body,
  Param,
  UseGuards,
  HttpCode,
  HttpStatus,
  Request,
  NotFoundException,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBearerAuth,
  ApiUnauthorizedResponse,
} from '@nestjs/swagger';
import { JwtAuthGuard } from '../user/guards/jwt-auth.guard';
import { InterviewService } from './interview.service';
import { CreateInterviewDto, SessionResponseDto } from './dto';
import { Interview } from './entities/interview.entity';
import {
  InterviewSession,
  InterviewSessionStatus,
} from './entities/interview-session.entity';
import { Answer } from './entities/answer.entity';

interface AuthenticatedRequest extends Request {
  user: {
    id: string;
    email: string;
    firstName?: string;
    lastName?: string;
  };
}

@ApiTags('interviews')
@ApiBearerAuth('JWT-auth')
@Controller('interviews')
@UseGuards(JwtAuthGuard)
export class InterviewController {
  constructor(private readonly interviewService: InterviewService) {}

  @Post('generate')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Generate technical interview questions',
    description:
      'Generates technical interview questions based on provided skills using OpenAI',
  })
  @ApiResponse({
    status: 200,
    description: 'Interview questions generated successfully',
    schema: {
      example: {
        questions: [
          {
            skill: 'JavaScript',
            question:
              'Explain the difference between let, const, and var in JavaScript.',
            difficulty: 'intermediate',
            category: 'conceptual',
          },
          {
            skill: 'React',
            question:
              'What is the difference between controlled and uncontrolled components?',
            difficulty: 'intermediate',
            category: 'conceptual',
          },
        ],
        totalQuestions: 6,
        skills: ['JavaScript', 'React'],
        difficulty: 'intermediate',
      },
    },
  })
  @ApiResponse({
    status: 400,
    description: 'Bad request - Invalid input or OpenAI API error',
  })
  @ApiUnauthorizedResponse({
    description: 'Unauthorized - Invalid or missing JWT token',
  })
  async generateInterview(
    @Request() req: AuthenticatedRequest,
    @Body() createInterviewDto: CreateInterviewDto,
  ) {
    const { skills, questionsPerSkill, difficulty, context } =
      createInterviewDto;

    return this.interviewService.generateInterview(
      req.user.id,
      skills,
      questionsPerSkill || 3,
      difficulty || 'intermediate',
      context,
    );
  }

  @Get()
  @ApiOperation({
    summary: 'Get all interviews for the authenticated user',
    description: 'Returns a list of all interviews generated by the user',
  })
  @ApiResponse({
    status: 200,
    description: 'List of interviews retrieved successfully',
  })
  @ApiUnauthorizedResponse({
    description: 'Unauthorized - Invalid or missing JWT token',
  })
  async getInterviews(
    @Request() req: AuthenticatedRequest,
  ): Promise<Interview[]> {
    return await this.interviewService.getUserInterviews(req.user.id);
  }

  @Get(':id')
  @ApiOperation({
    summary: 'Get a specific interview by ID',
    description:
      'Returns a single interview if it belongs to the authenticated user',
  })
  @ApiResponse({
    status: 200,
    description: 'Interview retrieved successfully',
  })
  @ApiResponse({
    status: 404,
    description: 'Interview not found',
  })
  @ApiUnauthorizedResponse({
    description: 'Unauthorized - Invalid or missing JWT token',
  })
  async getInterview(
    @Request() req: AuthenticatedRequest,
    @Param('id') id: string,
  ): Promise<Interview> {
    const interview = await this.interviewService.getInterviewById(
      id,
      req.user.id,
    );
    if (!interview) {
      throw new NotFoundException('Interview not found');
    }
    return interview;
  }

  @Post(':interviewId/start')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Start a new interview session',
    description:
      'Creates a new interview session and returns the first question immediately.',
  })
  @ApiResponse({
    status: 201,
    description: 'Interview session started successfully',
    type: SessionResponseDto,
  })
  @ApiResponse({
    status: 404,
    description: 'Interview not found',
  })
  @ApiUnauthorizedResponse({
    description: 'Unauthorized - Invalid or missing JWT token',
  })
  async startInterview(
    @Request() req: AuthenticatedRequest,
    @Param('interviewId') interviewId: string,
  ) {
    const { session, question } =
      await this.interviewService.startInterviewSession(
        req.user.id,
        interviewId,
      );

    const interview = await this.interviewService.getInterviewById(
      interviewId,
      req.user.id,
    );

    return {
      sessionId: session.id,
      questionIndex: 0,
      questionId: 'question-0',
      questionText: question.question,
      totalQuestions: interview?.totalQuestions || 1,
      skill: question.skill || 'general',
      difficulty: question.difficulty || 'intermediate',
    };
  }

  @Get('sessions')
  @ApiOperation({
    summary: 'Get all interview sessions for the authenticated user',
    description: 'Returns a list of all interview sessions created by the user',
  })
  @ApiResponse({
    status: 200,
    description: 'List of interview sessions retrieved successfully',
    type: [SessionResponseDto],
  })
  @ApiUnauthorizedResponse({
    description: 'Unauthorized - Invalid or missing JWT token',
  })
  async getSessions(
    @Request() req: AuthenticatedRequest,
  ): Promise<InterviewSession[]> {
    return await this.interviewService.getUserSessions(req.user.id);
  }

  @Get('sessions/:sessionId')
  @ApiOperation({
    summary: 'Get a specific interview session by ID',
    description:
      'Returns session details with answers and evaluations if completed',
  })
  @ApiResponse({
    status: 200,
    description: 'Interview session retrieved successfully',
    type: SessionResponseDto,
  })
  @ApiResponse({
    status: 404,
    description: 'Interview session not found',
  })
  @ApiUnauthorizedResponse({
    description: 'Unauthorized - Invalid or missing JWT token',
  })
  async getSession(
    @Request() req: AuthenticatedRequest,
    @Param('sessionId') sessionId: string,
  ): Promise<InterviewSession> {
    return await this.interviewService.getSessionById(sessionId, req.user.id);
  }

  @Get('sessions/:sessionId/answers')
  @ApiOperation({
    summary: 'Get all answers for an interview session',
    description: 'Returns all answers submitted during the interview session',
  })
  @ApiResponse({
    status: 200,
    description: 'Answers retrieved successfully',
    type: [Answer],
  })
  @ApiResponse({
    status: 404,
    description: 'Interview session not found',
  })
  @ApiUnauthorizedResponse({
    description: 'Unauthorized - Invalid or missing JWT token',
  })
  async getSessionAnswers(
    @Request() req: AuthenticatedRequest,
    @Param('sessionId') sessionId: string,
  ): Promise<Answer[]> {
    return await this.interviewService.getSessionAnswers(
      sessionId,
      req.user.id,
    );
  }

  @Post('sessions/:sessionId/answers')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Submit an answer for a question',
    description: 'Submits an answer for the current question in the session',
  })
  @ApiResponse({
    status: 201,
    description: 'Answer submitted successfully',
  })
  @ApiResponse({
    status: 404,
    description: 'Interview session not found',
  })
  @ApiUnauthorizedResponse({
    description: 'Unauthorized - Invalid or missing JWT token',
  })
  async submitAnswer(
    @Request() req: AuthenticatedRequest,
    @Param('sessionId') sessionId: string,
    @Body() body: { questionId: string; questionIndex: number; answer: string },
  ) {
    await this.interviewService.submitAnswer(
      sessionId,
      body.questionIndex,
      body.answer,
      req.user.id,
    );

    return {
      success: true,
      message: 'Answer received',
    };
  }

  @Post('sessions/:sessionId/next')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Get the next question',
    description:
      'Moves to the next question and returns it, or null if no more questions',
  })
  @ApiResponse({
    status: 200,
    description: 'Next question retrieved successfully',
  })
  @ApiResponse({
    status: 404,
    description: 'Interview session not found',
  })
  @ApiUnauthorizedResponse({
    description: 'Unauthorized - Invalid or missing JWT token',
  })
  async getNextQuestion(
    @Request() req: AuthenticatedRequest,
    @Param('sessionId') sessionId: string,
  ) {
    const question = await this.interviewService.moveToNextQuestion(
      sessionId,
      req.user.id,
    );

    if (!question) {
      return {
        questionIndex: null,
        questionId: null,
        questionText: null,
        isLastQuestion: true,
        totalQuestions: 0,
      };
    }

    const session = await this.interviewService.getSessionById(
      sessionId,
      req.user.id,
    );
    const interview = await this.interviewService.getInterviewById(
      session.interviewId,
      req.user.id,
    );

    if (!interview) {
      throw new NotFoundException('Interview not found');
    }

    return {
      questionIndex: session.currentQuestionIndex,
      questionId: `question-${session.currentQuestionIndex}`,
      questionText: question.question,
      isLastQuestion:
        session.currentQuestionIndex === interview.questions.length - 1,
      totalQuestions: interview.totalQuestions,
      skill: question.skill || 'general',
      difficulty: question.difficulty || 'intermediate',
    };
  }

  @Get('sessions/:sessionId/status')
  @ApiOperation({
    summary: 'Get interview session status',
    description: 'Returns the current status of the interview session',
  })
  @ApiResponse({
    status: 200,
    description: 'Session status retrieved successfully',
  })
  @ApiResponse({
    status: 404,
    description: 'Interview session not found',
  })
  @ApiUnauthorizedResponse({
    description: 'Unauthorized - Invalid or missing JWT token',
  })
  async getSessionStatus(
    @Request() req: AuthenticatedRequest,
    @Param('sessionId') sessionId: string,
  ) {
    const session = await this.interviewService.getSessionById(
      sessionId,
      req.user.id,
    );
    const interview = await this.interviewService.getInterviewById(
      session.interviewId,
      req.user.id,
    );

    if (!interview) {
      throw new NotFoundException('Interview not found');
    }

    return {
      sessionId: session.id,
      status: session.status,
      currentQuestionIndex: session.currentQuestionIndex,
      totalQuestions: interview.totalQuestions,
      isComplete: session.status === InterviewSessionStatus.COMPLETED,
    };
  }

  @Post('sessions/:sessionId/complete')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Manually complete an interview session',
    description:
      'Marks the interview as complete and triggers batch evaluation of all answers',
  })
  @ApiResponse({
    status: 200,
    description: 'Interview completed successfully with evaluations',
    schema: {
      example: {
        session: {},
        evaluations: [
          {
            questionIndex: 0,
            score: 8.5,
            feedback: 'Good answer',
            strengths: ['Clear explanation'],
            weaknesses: ['Could provide more detail'],
          },
        ],
        overallScore: 8.2,
        summary: 'Overall assessment',
        recommendations: ['Recommendation 1'],
      },
    },
  })
  @ApiResponse({
    status: 404,
    description: 'Interview session not found',
  })
  @ApiUnauthorizedResponse({
    description: 'Unauthorized - Invalid or missing JWT token',
  })
  async completeSession(
    @Request() req: AuthenticatedRequest,
    @Param('sessionId') sessionId: string,
  ) {
    return await this.interviewService.completeInterview(
      sessionId,
      req.user.id,
    );
  }
}
